name: rapppid
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
  - pytorch-lightning>=1.3.8
  - cudatoolkit=11.1
  - sqlite=3.40.1
  - scikit-learn>=1.2.0
  - sentencepiece>=0.1.97
  - passlib=1.7.4
  - fire
  - matplotlib
  - tqdm
  - jupyter
  - pip
  - pip:
    - tables==3.8.0
    - git+https://github.com/lessw2020/Ranger21.git
